# Chapter 12-02
## NumPyを使う

### NumPyのarrayを生成する

In [ ]:
import numpy as np         # NumPyをインポート
a = np.array([0, 1, 2, 3]) # arrayを作る
a                          # arrayを表示

In [ ]:
# 二次元のarrayを表示
b = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

b

In [ ]:
# arrayのアトリビュートを表示
print(b.ndim)       # 次元数
print(b.shape)      # 各次元の要素数
print(b.size)       # サイズ
print(b.dtype)      # 型

In [ ]:
# reshape()でarrayの形を変える
b2 = np.zeros(9).reshape(3, 3)
b2

In [ ]:
# T(転置行列)を表示
# 0,1,2 2,3,4 5,6,7という3x3のarray
a = np.arange(9).reshape(3, 3)  
a.T                   # 90度回転したarrayを表示

### arrayを使った演算

In [ ]:
# arrayの各要素に1を足す
a = np.arange(1, 10)    # 1から9までの配列を作る
a+1                     # 各要素に1を足して表示

In [ ]:
# 2つのarrayの各要素を足す
a = np.arange(1, 10)
b = np.arange(1, 10)    # 1から9までの配列をふたつ作る
a+b                     # aの要素とbの要素を足す

In [ ]:
# ブロードキャスティング(Broadcasting)
a = np.ones(9).reshape(3, 3) # 1だけで構成された3x3のarrayを作る
b = np.arange(1, 4)          # 1, 2, 3のarray作る
a*b                          # かけ算した結果を表示

In [ ]:
# ブロードキャスティングを使って3x3のarrayを作る
np.zeros((3, 1))*np.zeros((1, 3))

In [ ]:
# 関数を使った演算
# 0,1,2 2,3,4 5,6,7という3x3のarray
a = np.arange(9).reshape(3, 3)
np.sum(a)        # 合計を計算

In [ ]:
# 引数axisを与えた演算
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]
# 上記配列の行ごとに合計を計算
np.sum(a, axis=0)

### 要素へのアクセス

In [ ]:
a = np.arange(9).reshape(3, 3) # 0から8まで，3x3のarrayを作る
a[1, 2]                        # 1, 2の要素を表示

In [ ]:
# スライスを使って要素にアクセスする
a[1:, 1:3]             # 右下の2×2の配列を取り出す

In [ ]:
# インデックスにシーケンスを渡して複数の要素にアクセスする
d = np.arange(1, 10)        # 1から9までのarrayを作る
d[[1, 3, 5, 7]]             # 偶数だけ取り出す

### arrayの連結

In [ ]:
# 横方向への連結
a = np.arange(4).reshape(2, 2)      #2x2,0から3までのarray
b = np.arange(5, 9).reshape(2, 2)   #2x2,5から8までのarray
np.hstack((a, b))

In [ ]:
# 縦方向への連結
a = np.arange(4).reshape(2, 2)      #2x2,0から3までのarray
b = np.arange(5, 9).reshape(2, 2)   #2x2,5から8までのarray
np.vstack((a, b))

### arrayのコピー

In [ ]:
# 組み込み型のリストと同様に，arrayの代入はコピーになる
# (変数が同一arrayへのリファレンスを持つ)
a = np.zeros(4)     # 4つの0でarrayを作る
b = a               # bに代入
b += 1              # 各要素に1を足す
a                   # aの内容を表示

In [ ]:
# あるarrayから別のarrayを生成したいときは，明示的にコピーする
a = np.zeros(4)     # 4つの0でarrayを作る
b = a.copy()        # bに代入
b += 1              # 各要素に1を足す
print(a)            # aの内容を表示